MyDocApp/Controllers/MyDocModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyDocApp.Data;
using MyDocApp.Models;

namespace MyDocApp.Controllers
{
    public class MyDocModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MyDocModelsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MyDocModels

        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.MyDocModel != null ? 
                          View(await _context.MyDocModel.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.MyDocModel'  is null.");
        }


        /// <summary>
        /// get method
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        /// <summary>
        /// post: myDocModelsController/ShowSearchResults
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> ShowSearchResult(string SearchPhrase)
        {
            return View("Index", await _context.MyDocModel.Where(j =>
            j.PatientsName.Contains(SearchPhrase)).ToListAsync());
        }




        // GET: MyDocModels/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MyDocModel == null)
            {
                return NotFound();
            }

            var myDocModel = await _context.MyDocModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myDocModel == null)
            {
                return NotFound();
            }

            return View(myDocModel);
        }

        // GET: MyDocModels/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: MyDocModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PatientsName,Street,DoctorsName,AppointmentData,PhoneNumber,Email,ZipCode,PainLevel,JPMGnumber,AboutPatient,PatientNetWorth,TreatmentDuration")] MyDocModel myDocModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(myDocModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(myDocModel);
        }

        // GET: MyDocModels/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MyDocModel == null)
            {
                return NotFound();
            }

            var myDocModel = await _context.MyDocModel.FindAsync(id);
            if (myDocModel == null)
            {
                return NotFound();
            }
            return View(myDocModel);
        }

        // POST: MyDocModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PatientsName,Street,DoctorsName,AppointmentData,PhoneNumber,Email,ZipCode,PainLevel,JPMGnumber,AboutPatient,PatientNetWorth,TreatmentDuration")] MyDocModel myDocModel)
        {
            if (id != myDocModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(myDocModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MyDocModelExists(myDocModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myDocModel);
        }

        // GET: MyDocModels/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MyDocModel == null)
            {
                return NotFound();
            }

            var myDocModel = await _context.MyDocModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myDocModel == null)
            {
                return NotFound();
            }

            return View(myDocModel);
        }

        // POST: MyDocModels/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MyDocModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.MyDocModel'  is null.");
            }
            var myDocModel = await _context.MyDocModel.FindAsync(id);
            if (myDocModel != null)
            {
                _context.MyDocModel.Remove(myDocModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        private bool MyDocModelExists(int id)
        {
          return (_context.MyDocModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MyDocApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyDocApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyDocApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyDocApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MyDocModels" asp-action="Index">Documentation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MyDocModels" asp-action="Create">Create </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MyDocModels" asp-action="ShowSearchForm">Search </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyDocApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>